USE apoyame;


/* ---------- CONSULTAS GENERALES ---------- */


-- USUARIO

SELECT * FROM USUARIO WHERE ID_USUARIO = 3;
SELECT EMAIL FROM USUARIO WHERE EMAIL LIKE '%gmail.com';

-- GRUPO

SELECT * FROM GRUPO WHERE ID_GRUPO = 2;
SELECT * FROM GRUPO WHERE NOMBRE LIKE "G%";

-- TEMA

SELECT * FROM TEMA WHERE ID_TEMA = 3;
SELECT * FROM TEMA WHERE  NUM_ENTRADAS > 3;

-- ENTRADA

SELECT * FROM ENTRADA WHERE ID_ENTRADA = 4;
SELECT * FROM ENTRADA
WHERE FECHA_HORA> 01-01-2021;

-- REUNIONVIRTUAL

SELECT * FROM REUNIONVIRTUAL WHERE ID_REUNION = 5;
SELECT * 
FROM REUNIONVIRTUAL
WHERE PLATAFORMA LIKE "ZOOM";

-- REUNIONPRESENCIAL

SELECT * FROM REUNIONPRESENCIAL WHERE ID_REUNION = 6;
SELECT * FROM REUNIONPRESENCIAL
WHERE FECHA_HORA > 2021-06-01;

-- ASISTENCIAREUNIONVIRTUAL

SELECT * FROM ASISTENCIAREUNIONVIRTUAL WHERE ID_ASISTENCIA = 7;
SELECT * FROM ASISTENCIAREUNIONVIRTUAL
WHERE ID_ASISTENCIA > 100 
AND ID_ASISTENCIA < 150;

-- ASISTENCIAREUNIONPRESENCIAL

SELECT * FROM ASISTENCIAREUNIONPRESENCIAL WHERE ID_ASISTENCIA = 8;
SELECT * FROM ASISTENCIAREUNIONPRESENCIAL
WHERE ID_ASISTENCIA < 100 ;

-- MIEMBROGRUPO

SELECT * FROM MIEMBROGRUPO WHERE ID_MEMBRESIA = 9;
SELECT * FROM MIEMBROGRUPO
WHERE ESTADO LIKE "INACTIVO";

-- CATALOGO

SELECT * FROM CATALOGO WHERE ID_CATALOGO = 10;
SELECT * FROM CATALOGO
WHERE TITULO_SECCION LIKE "TITULO%";

-- VIDEO

SELECT * FROM VIDEO WHERE ID_VIDEO = 11;
SELECT * FROM VIDEO
WHERE TITULO LIKE "VIDEO%";

-- ARTICULO

SELECT * FROM ARTICULO WHERE ID_ARTICULO = 12;
SELECT EMAIL AS CORREO_AUTOR, TITULO AS TITULO_ARTICULO, length(TEXTO) as NUM_CARACTERES_ARTICULO
FROM ARTICULO
JOIN USUARIO
ON ARTICULO.ID_AUTOR = USUARIO.ID_USUARIO
WHERE USUARIO.NICKNAME LIKE 'WolfZard';


/* -------------- CONSULTAS QUE SE EMPLEARÍAN PARA DESARROLLAR LA APLICACIÓN -------------- */


-- CONSULTAS PARA PROCESO 3: Ingresar Categorías del Usuario

-- OBTENIENDO LAS DISTINTAS CATEGORÍAS DE LOS GRUPOS EXISTENTES:

SELECT DISTINCT CATEGORIA FROM GRUPO;

-- EJEMPLO DE CATEGORIAS SELECCIONADAS POR EL USUARIO: 'EXPERIENCIAS', 'ABUSO'

SELECT NOMBRE AS GRUPO, CATEGORIA 
FROM GRUPO 
WHERE CATEGORIA IN ('EXPERIENCIAS', 'ABUSO');


-- CONSULTAS PARA PROCESO 6: Buscar Grupo de Apoyo

-- EJEMPLO DE INSERCIÓN DEL USUARIO EN EL CUADRO DE BÚSQUEDA: 'A'
-- EJEMPLOS DE SELECCIONES DE FILTROS:
    -- NÚMERO DE USUARIOS: Menor a 50
    
SELECT GRUPO.NOMBRE AS GRUPO, COUNT(USUARIO.ID_USUARIO) AS NUMERO_USUARIOS
FROM GRUPO
JOIN MIEMBROGRUPO
ON GRUPO.ID_GRUPO = MIEMBROGRUPO.ID_GRUPO
JOIN USUARIO
ON MIEMBROGRUPO.ID_USUARIO = USUARIO.ID_USUARIO
WHERE GRUPO.NOMBRE LIKE '%A%'
GROUP BY GRUPO
HAVING NUMERO_USUARIOS < 50;


-- CONSULTAS PARA PROCESO 9: Buscar Temas

-- EJEMPLO DE INSERCIÓN DEL USUARIO EN EL CUADRO DE BÚSQUEDA: 'TEMA 1'
-- EJEMPLO DE SELECCIÓN DE GRUPO DONDE QUIERE BUSCAR EL USUARIO AL TEMA EN CUESTIÓN: 'MI REFLEJO'

SELECT T.NOMBRE AS NOMBRE_TEMA, DATE(T.F_CREACION) AS FECHA_CREACION, T.NUM_ENTRADAS AS ENTRADAS
FROM TEMA T
JOIN GRUPO G
ON T.ID_GRUPO = G.ID_GRUPO
WHERE T.NOMBRE LIKE '%TEMA 1%'
AND G.NOMBRE LIKE 'MI REFLEJO';


