USE apoyame;

INSERT INTO USUARIO(NICKNAME, NOMBRE, EMAIL, CONTRASEÑA) VALUES 
("HugoX", "Hugo Fernando", "elhugox@hotmail.com", "q1w2e3"),
("Samsville", "Samantha Sánchez", "samsville@gmail.com", "kilobolo10"),
("JGorGG", "Henry Quinionez", "JGorGG@hotmail.com", "ZXASQW12"),
("WolfZard", "Giancarlo Carvajal", "reloaded1100@gmail.com", "tutankamon"),
("MariYas", "María Hernández", "marimeri@hotmail.com", "gorki9912"),
("mediaattentive","Janice Keenan","mediaattentive@gmail.com","n8FYSr"),
("tawdryfailure","Ravi Mcloughlin","tawdryfailure@gmail.com","Gn0bIC"),
("cyanslimy","Winnie Rosario","cyanslimy@gmail.com","Z0Iq2w"),
("cerebrumapplaud","Petra Mckinney","cerebrumapplaud@gmail.com","Hau04q"),
("assistantdiamonds","Shaunna Andrews","assistantdiamonds@gmail.com","4jO0Tm"),
("promotefibula","Hunter Thorpe","promotefibula@gmail.com","Tr0U1K"),
("lumberingcoaming","Marcus Bray","lumberingcoaming@gmail.com","PvG6dR"),
("evenauction","Sallie Wallis","evenauction@gmail.com","pZFB3a"),
("scalytrot","Adina Mcmillan","scalytrot@gmail.com","v1nJAr"),
("wiltedstrut","Eshaal Liu","wiltedstrut@gmail.com","mFZC3r"),
("aroundmeniscus","Humayra Mccabe","aroundmeniscus@gmail.com","Tf9vVx"),
("physicalsalmon","Beverly Hanson","physicalsalmon@gmail.com","D7d9N1"),
("lasagnealcohol","Jiya Allison","lasagnealcohol@gmail.com","m1CEYD"),
("inventivebadly","Clarissa Alford","inventivebadly@gmail.com","hdr2MH"),
("criticmedicine","Mahi Casey","criticmedicine@gmail.com","IZ5gkh");

INSERT INTO GRUPO(NOMBRE, DESCRIPCION, CATEGORIA) VALUES 
("TODOS CONTRA EL BULLYING","EN ESTE GUPO SE ENCUENTRAN TEMAS RELACIONADOS CON EL BULLYING","BULLYING"),
("APOYO CONTRA EL ABUSO","GRUPO EN DONDE SE APOYA A LAS PERSONAS QUE SUFREN DE ABUSO","ABUSO"),
("TOD@S CONTRA EL ABUSO EN EL COLEGIO","COSAS QUE PUEDES HACER EN EL COLEGIO EN CASO QUE SUFRAS ALGUN TIPO DE ABUSO","ABUSO"),
("BULLYING EN COLEGIO","EN ESTE GRUPO ENCONTRARAS MEDIDAS QUE PUEDES TOMAR EN CASO DE QUE SUFRAS DE BULLING EN EL COLEGIO","BULLYING"),
("¿QUE HACER EN CONTRA DEL BULLING?","GRUPO EN DONDE COMENTAN SITUACIONES EN DONDE LAS PERSONAS SUFRIERON O SUFREN BULLYING, Y QUE HACEN PARA ERRADICARLO","BULLYING"),
("PROHIBIDO RENDIRSE", "AQUÍ ENCONTRARÁS APOYO PARA NO RENDIRTE", "SUPERACIÓN"),
("UNIDOS POR EL OBJETIVO", "GRUPO PARA COMPARTIR METAS Y BRINDAR APOYO EN SU CUMPLIMIENTO", "SUPERACIÓN"),
("HÉROES SILENCIOSOS", "GRUPO DONDE SE COMPARTEN EXPERIENCIAS FUERTES E INSPIRADORAS", "EXPERIENCIAS"),
("ROMPIENDO REGLAS", "CUÉNTANOS TUS EXPERIENCIAS LIBERADORAS", "EXPERIENCIAS"),
("GRUPO NOBLE", "SIÉNTETE LIBRE DE CONTAR LAS COSAS DE LAS QUE TE SIENTES ORGULLOSO", "SUPERACIÓN"),
("SIN LÍMITES", "SOLO HISTORIAS DE SUPERACIÓN", "SUPERACIÓN"),
("NO MÁS DOLOR", "LIBERA AQUELLO QUE NO LE CUENTAS A NADIE Y SANA DE UNA VEZ POR TODAS", "EXPERIENCIAS"),
("GUARIDA DE SECRETOS", "DEJA SALIR AQUELLO QUE YA NO ES TU CULPA", "EXPERIENCIAS"),
("LEVANTANDO CABEZAS", "APOYO DE TODOS PARA TODOS", "SUPERACIÓN"),
("DOSIS DE REALIDAD", "CUÉNTANOS LAS COSAS QUE TE HICIERON DAR CUENTA DE QUE NECESITABAS UN CAMBIO", "EXPERIENCIAS"),
("PODER MENTAL", "APRENDE A EDUCAR TU MENTE Y SUS EMOCIONES", "SUPERACIÓN"),
("AMIGOS EVERYWHERE", "SOLO COSAS RANDOM DE AMIGOS HACIA AMIGOS", "EXPERIENCIAS"),
("SIN MIEDO A ERRORES", "ANÍMATE A COMPARTIR TUS EQUIVOCACIONES Y LO QUE APRENDISTE DE ELLAS", "EXPERIENCIAS"),
("MI FOBIA Y YO", "AQUÍ SE COMPARTEN LAS EXPERIENCIAS DE UNA VIDA CON FOBIAS", "EXPERIENCIAS"),
("MI REFLEJO", "¿QUÉ PIENSAS DE TI? ¿QUÉ TE GUSTARÍA CAMBIAR?", "EXPLORACIÓN PERSONAL");

INSERT INTO MIEMBROGRUPO(ID_USUARIO, ID_GRUPO) VALUES
(1, 18),
(2, 15),
(3, 15),
(4, 15),
(5, 15),
(6, 7),
(7, 7),
(8, 15),
(9, 5),
(10, 4),
(11, 17),
(12, 15),
(13, 15),
(14, 2),
(15, 19),
(16, 15),
(17, 20),
(18, 3),
(19, 3),
(20, 3);

INSERT INTO TEMA(NOMBRE, ID_CREADOR, ID_GRUPO) VALUES
("TEMA 1", 1, 18),
("TEMA 2", 2, 15),
("TEMA 3", 3, 15),
("TEMA 4", 4, 15),
("TEMA 5", 5, 15),
("TEMA 6", 6, 7),
("TEMA 7", 7, 7),
("TEMA 8", 8, 15),
("TEMA 9", 9, 5),
("TEMA 10", 10, 4),
("TEMA 11", 11, 17),
("TEMA 12", 12, 15),
("TEMA 13", 13, 15),
("TEMA 14", 14, 2),
("TEMA 15", 15, 19),
("TEMA 16", 16, 15),
("TEMA 17", 17, 20),
("TEMA 18", 18, 3),
("TEMA 19", 19, 3),
("TEMA 20", 20, 3);

INSERT INTO ENTRADA(ID_AUTOR, ID_TEMA, TEXTO) VALUES
(5, 5, "Mi primera entrada"),
(4, 4, "Creo que sí deberías hacerlo."),
(3, 3, "Yo tambien creo lo mismo :)"),
(2, 2, "¿Y porque no hiciste eso antes de que empeorara el problema?"),
(1, 1, "Deberías tomarlo con más calma."),
(6, 6, "Consulta con un profesional"),
(7, 7, "Tranqui, es normal de la edad"),
(8, 8, "Deberías concentrarte en controlar tus sentimientos"),
(9, 9, "Claro que sí"),
(10, 10, "Claro que no"),
(20, 20, "Tambien tengo el mismo probelma"),
(19, 19, "Menos mal ocurrió así."),
(18, 18, "Pudo haber sido peor"),
(17, 17, "No lo se amigo, nunca me ha pasado"),
(16, 16, "Me ocurrió algo similar!"),
(15, 15, "Deberiamos de hacer una videollamada"),
(14, 14, "Habla con un familiar sobre el tema"),
(13, 13, "Decirte que no es mentirte"),
(12, 12, "No lo sé, quizas sí"),
(11, 11, "Cuídate mucho!");

INSERT INTO REUNIONVIRTUAL(ID_ORGANIZADOR, ID_TEMA, PLATAFORMA) VALUES
(10, 10, "ZOOM"),
(20, 20, "WHATSAPP"),
(19, 19, "HABBO HOTEL"),
(18, 18, "ZOOM"),
(17, 17, "ZOOM"),
(16, 16, "WHATSAPP"),
(15, 15, "FACEBOOK"),
(14, 14, "WOW"),
(13, 13, "MINECRAFT"),
(12, 12, "MINECRAFT"),
(11, 11, "ZOOM"),
(5, 5, "WHATSAPP"),
(4, 4, "ZOOM"),
(3, 3, "ZOOM"),
(2, 2, "HABBO HOTEL"),
(1, 1, "ZOOM"),
(6, 6, "WHATSAPP"),
(7, 7, "WHATSAPP"),
(8, 8, "MINECRAFT"),
(9, 9, "ZOOM");

INSERT INTO REUNIONPRESENCIAL(ID_ORGANIZADOR, ID_TEMA, UBICACION) VALUES
(10, 1, "Rochdale"),
(15, 10, "Garrigill"),
(8, 6, "Dumbarton"),
(12, 14, "Hillford"),
(19, 4, "Westwend"),
(4, 6, "Duncaster"),
(5, 8, "Putlochry"),
(18, 3, "Newham"),
(1, 15, "Davenport"),
(16, 13, "Abingdon"),
(20, 11, "Northwich"),
(17, 1, "Braedon"),
(2, 18, "Domburton"),
(3 ,19 , "Ballater"),
(13, 20, "Blackridgepool"),
(6, 8, "Burnsley"),
(11, 14, "Caerleon"),
(9, 13, "Arkmunster"),
(14, 15, "Bury"),
(7, 4, "Penrith");

INSERT INTO ASISTENCIAREUNIONVIRTUAL(ID_ASISTENTE, ID_REUNION) VALUES
(10, 10),
(19, 19),
(18, 18),
(17, 17),
(9, 9),
(20, 20),
(13, 13),
(12, 12),
(11, 11),
(5, 5),
(4, 4),
(16, 16),
(15, 15),
(14, 14),
(6, 6),
(7, 7),
(8, 8),
(3, 3),
(2, 2),
(1, 1);

INSERT INTO ASISTENCIAREUNIONPRESENCIAL(ID_ASISTENTE, ID_REUNION) VALUES
(3, 3),
(2, 2),
(20, 20),
(13, 13),
(12, 12),
(19, 19),
(18, 18),
(11, 11),
(4, 4),
(10, 10),
(17, 17),
(9, 9),
(16, 16),
(15, 15),
(14, 14),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(1, 1);

INSERT INTO CATALOGO(TITULO_SECCION, ID_GRUPO) VALUES
("Abuso en la Adolescencia", 2),
("Abuso en la Adultez", 2),
("Rol de los Padres", 3),
("Definiciones", 1),
("Profesores y el Bullying", 4),
("Para los Bullies", 5),
("Procrastinación", 7),
("Confianza", 9),
("Culpabilidad", 8),
("Definiendo Metas", 6),
("Victorias", 10),
("El Cerebro", 16),
("Liberación", 13),
("Desahogo", 12),
("Círculos Viciosos", 14),
("Poder Mental", 11),
("Proceso de Mejora", 18),
("Autoconocimiento", 20),
("Autoayuda", 19),
("Afrontar las Experiencias", 15);

INSERT INTO ARTICULO(ID_AUTOR, TITULO, ID_CATALOGO, TEXTO) VALUES
(6,"Como evitar el bulling",2,"Lo mejor que puede hacer si sufres de bulling es tener contacto con una persona mayor con la cual te sientas en confianza de contarle lo que esta ocurriendo y el seguramente te va a ayudar con lo que te esta ocurriendo"),
(7,"Ayuda para las personas que sufren de insomnio",2,"A largo plazo este se pueda convertir en una enfermedad y puede te puede afectar de varias maneras tu organismo por lo que a pesar de estar despierto toda la noche lo recomendable es que puedas tener tus horas diarias de sueño"),
(8,"Como evitar confictos en la escuela",4,"La manera mas sana para no tener inconvenientes en la escuela es juntarte con las personas que tengan los mismos gutos que tu y lo mas probable es que al tener los mismo gustos no tengan inconvenientes"),
(9,"Pasos para evitar la ira",6,"Todos sabemos que en algun momento pasamos por varios estados en los que las iras que tenemos son incontenibles y que llegara el dia en el que no vas a aguantar mas, por lo que te recomendamos que antes de explotar lo comentes con una personas a la cual le tengas confianza de manera relajada "),
(10,"Que hacer en caso de ansiedad",5,"Las personas que tienen problemas de ansiedad es recomendable que mantengan la calma y sepan sobrellevar la situacion, es mucho mejor si estas acompañad@ de una persona de confianza"),
(6,"La importancia de la salud mental",8,"La salud mental es algo a lo que las personas no le ponen importancia porque lo toman como algo que fuese normal del dia a dia, pero la realidad es que a largo plazo esto puede afectar gravemente a las personas "),
(11,"Que es lo que hace un psicologo",9,"Los psicologos en general tratan de ayudar a las peronas a darle opciones que puedan realizar en base a los problemas que tienen"),
(12,"¿En que te ayuda un psicologo a tu salud?",7,"El psicologo lo que hace es ayudar a las personas estabilizar la salud mental de las personas"),
(13,"¿Porque es importante tener una salud mental estable?",4,"Lo mas importante para las personas es que tengan una salud estable ya sea fisica como mental ya que con salud las peronas puedan llegar a realizar todos sus logros"),
(14,"Por que no debes de pasar por alto tu salud mental",6,"Porque probablemente existan personas que por falta de informacion no tengan muy claro sobre las cosas que estan pasando y por la acumulacion de todos esos problemas pueden afectar gravemente la salud"),
(14,"Que hacer si ves que una persona esta sufriendo de ansiedad",10,"Primero identificar que verdaderamente este sufriendo de ansiedad, y ayudar lo mas pronto posible trantando de estabilizar a la persona que esta pasando por eso"),
(6,"Como ayudar a que las personas se sientan mejor emocionalmente",11,"En su mayoria las personas buscan sentirse bien para poder realizar las cosas cotidianas y muchas veces no es necesario acudir a un especialista necesariamente, muchas veces solo es necesario escuchar y prestar atencion a las personas para que se sientan mejor"),
(4,"Como hacer que las personas de tercera edad se sientan bien emocionalmente",16,"Muchas veces no es necesario llevarle cosas meteriales a las personas simplemente con escuchar a las personas y prestarle algo de atencion es mas que suficiente"),
(5,"Actividades que te pueden ayudar a sentirte mejor contigo mismo",19,"En general en los momentos en lo que las personas se sienten mal lo mas recomendable es que ellas se encuentren ocupadas haciendo lo que mas le agrade como tocar algun instrumento o cocinar"),
(6,"Que hacer si te sientes mal emocionalmente",17,"Depende de el caso en el que te encuentres en casi de estar solo tratar de buscar a alguien con quien tener alguna conversacion, lo mas seguro es que si es una persona de confianza te pueda ayudar demasiado a mejorar"),
(7,"Que hacer para priorizar tu salud mental",18,"Tratar de estar bien con uno mismo en todos los sentidos ya sea fisica y mentalmente tratandod de hacer las cosas que mas te agranden a menudo trantando de estar bien contigo mismo"),
(14,"Como dar atencion a la salud mental de otras personas sin ser un psicologo",16,"Lo mas seguro es que muchas veces las personas necesiten ser atendidos por otra persona ya que no nos buscana una persona para que le de solucion a sus problemas que que solo se quieren sentir escuchados por alguien mas"),
(19,"Como apoyar emocionalmente a las demas personas",13,"Ayudandole a recapacitar sobre los problemas que tienen las demas personas quizas viendo que es lo que lo causa"),
(11,"La importancia de la salud mental en la vida de las personas",11,"Lo mas seguro es que si tienes una salud mental estable puedas llegar a lograr muchas cosas que te propongas asi mismo te ayuda a que te sientas bien contigo mismo y con la mayoria de cosas que te rodean"),
(7,"porque la salud mental es indispensable para el ser humano",20,"porque permite que las personas se puedan sentir estables y bien consigo mismo");

INSERT INTO VIDEO(URL, TITULO, ID_CATALOGO, DESCRIPCION) VALUES
("https://youtu.be/QH2-TGUlwu4", "10 Ways To Immediately Start Selling HELP", 1, "HELP Money Experiment"),
("https://youtu.be/Dot2Na4NwQQ", "3 Things Everyone Knows About HELP That You Don't", 2, "Your Weakest Link: Use It To HELP"),
("https://youtu.be/sAit66qi-EI", "14 Days To A Better HELP", 3,"The Complete Guide To Understanding HELP"),
("https://youtu.be/CrxoKZwQGxw", "The Lazy Way To HELP", 4,"Need More Inspiration With HELP? Read this!"),
("https://youtu.be/bSOfotKE0PE", "If You Want To Be A Winner, Change Your HELP Philosophy Now!", 5, "HELP - Pay Attentions To These 10 Signals"),
("https://youtu.be/XuWc_3j2VPs", "3 Ways You Can Reinvent HELP Without Looking Like An Amateur", 6,"Mastering The Way Of HELP Is Not An Accident - It's An Art"),
("https://youtu.be/yT16_7Jizn8", "Succeed With HELP In 24 Hours", 7,"Three Quick Ways To Learn HELP"),
("https://youtu.be/yJGuv5YuH9U", "Are You Making These HELP Mistakes?",8,"Marketing And HELP"),
("https://youtu.be/YwonxZP7y1o", "How We Improved Our HELP In One Week(Month, Day)", 9,"Read This To Change How You HELP"),
("https://youtu.be/6oHYgG5DFSM", "It's All About (The) HELP", 10, "3 Kinds Of HELP: Which One Will Make The Most Money?"),
("https://youtu.be/vQP5S-QBFfc", "Stop Wasting Time And Start HELP", 11, "HELP Like A Pro With The Help Of These 5 Tips"),
("https://youtu.be/rZScv5KZJQE", "Get The Most Out of HELP and Facebook", 12, "Amateurs HELP But Overlook A Few Simple Things"),
("https://youtu.be/PcsUqPbZuD8", "Top 25 Quotes On HELP", 13, "4 Key Tactics The Pros Use For HELP"),
("https://youtu.be/RNssmVzgsjE", "How To Make Your HELP Look Amazing In 5 Days", 14, "HELP – Lessons Learned From Google"),
("https://youtu.be/Jo6fKboqfMs", "HELP And Love - How They Are The Same", 15, "10 Creative Ways You Can Improve Your HELP"),
("https://youtu.be/9jr9xlqDMxg", "5 Easy Ways You Can Turn HELP Into Success", 16, "The Business Of HELP"),
("https://youtu.be/xvqg2IMUTa8", "What Can Instagramm Teach You About HELP", 17, "The World's Worst Advice On HELP"),
("https://youtu.be/ctEbPPy5YgY", "Boost Your HELP With These Tips", 18, "Who is Your HELP Customer?"),
("https://youtu.be/mIKSjETHrmY", "13 Myths About HELP", 19, "What $325 Buys You In HELP"),
("https://youtu.be/v5HpqAYK6iU", "Proof That HELP Is Exactly What You Are Looking For", 20, "Believing Any Of These 10 Myths About HELP Keeps You From Growing");
